version: "3.8"
services:
  postlite:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    platform: linux/amd64
    ports:
      - "5434:5432"
    volumes:
      - ./data:/data
